---
- name: Fetch SSH Key from Workstation
  hosts: workstation
  become: yes
  tasks:
    - name: Fetch standard user public key from workstation
      fetch:
        src: "{{ gdc_home }}/.ssh/id_rsa.pub"
        dest: /tmp/ws_id_rsa.pub
        flat: yes

- name: Setup SSH Access and Base OS on Cluster Nodes
  hosts: cluster_nodes
  become: yes
  roles:
    - cluster_nodes

- name: Setup VxLAN on all GCE instances
  hosts: gdc_nodes
  become: yes
  roles:
    - vxlan

- name: Deploy Google Distributed Cloud Hybrid Cluster
  hosts: workstation
  become: yes
  vars:
    cluster_name: "{{ tf_cluster_name }}"
  roles:
    - gdc_deploy
    - topolvm
    - gatekeeper
    - secondary_networks
