---
- name: Prepare Administrative Workstation
  hosts: workstation
  become: yes
  roles:
    - workstation

- name: Setup SSH Access and Base OS on Cluster Nodes
  hosts: cluster_nodes
  become: yes
  roles:
    - cluster_nodes

- name: Setup Edge Router
  hosts: edge_router
  become: yes
  roles:
    - edge_router

- name: Setup VxLAN on all GCE instances
  hosts: gdc_nodes
  become: yes
  roles:
    - vxlan

- name: Deploy Google Distributed Cloud Hybrid Cluster
  hosts: workstation
  become: yes
  vars:
    cluster_name: "{{ tf_cluster_name }}"
  roles:
    - gdc_deploy
    - topolvm
    - gatekeeper
    - secondary_networks
