gcrKeyPath: baremetal/gcr.json
sshPrivateKeyPath: .ssh/id_rsa
gkeConnectAgentServiceAccountKeyPath: baremetal/connect-agent.json
gkeConnectRegisterServiceAccountKeyPath: baremetal/connect-register.json
cloudOperationsServiceAccountKeyPath: baremetal/cloud-ops.json
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-edge-ha
---
apiVersion: baremetal.cluster.gke.io/v1
kind: Cluster
metadata:
  name: edge-ha
  namespace: cluster-edge-ha
spec:
  type: standalone
  profile: edge
  anthosBareMetalVersion: 1.34.200-gke.68
  gkeConnect:
    projectID: project-fleet
  controlPlane:
    nodePoolSpec:
      nodes:
      - address: 10.200.0.2
      - address: 10.200.0.3
      - address: 10.200.0.4
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/20
  loadBalancer:
    mode: bundled
    ports:
      controlPlaneLBPort: 443
    vips:
      controlPlaneVIP: 10.200.0.71
      ingressVIP: 10.200.0.72
    addressPools:
    - name: pool1
      addresses:
      - 10.200.0.72-10.200.0.90
  clusterOperations:
    projectID: project-fleet
    location: us-central1
  storage:
    lvpNodeMounts:
      path: /mnt/localpv-disk
      storageClassName: local-disks
    lvpShare:
      path: /mnt/localpv-share
      storageClassName: local-shared
      numPVUnderSharedPath: 5
  nodeConfig:
    podDensity:
      maxPodsPerNode: 110


controlPlane:
    apiServerArgs:
    - name: authorization-mode
      value: Node,Webhook,RBAC
    - file:
        configMap:
          name: auth-webhook-configmap
        key: file-content
      name: authorization-webhook-config-file
    nodePoolSpec:
      clusterName: ci003
      kubeletConfig:
        kubeReserved:
          cpu: 2400m
          memory: 10240Mi
        shutdownGracePeriod: 30s
        shutdownGracePeriodCriticalPods: 10s
        systemReserved:
          cpu: 2400m
          memory: 10240Mi
      labels:
        edgecontainer.googleapis.com/network-sriov.capable: "true"
      nodes:
      - address: 192.168.120.12
        labels:
          edgecontainer.googleapis.com/rack: gmec-luk66
          node.baremetal.cluster.gke.io/upgrade-stage: control-plane-0
          robin.io/rack: gmec-luk66
      - address: 192.168.120.13
        labels:
          edgecontainer.googleapis.com/rack: gmec-luk66
          node.baremetal.cluster.gke.io/upgrade-stage: control-plane-1
          robin.io/rack: gmec-luk66
      - address: 192.168.120.14
        labels:
          edgecontainer.googleapis.com/rack: gmec-luk66
          node.baremetal.cluster.gke.io/upgrade-stage: control-plane-2
          robin.io/rack: gmec-luk66
      operatingSystem: linux
      taints:
      - effect: PreferNoSchedule
        key: node-role.kubernetes.io/master
      - effect: PreferNoSchedule
        key: node-role.kubernetes.io/control-plane
  gkeConnect:
    location: global
    projectID: kr-9985-edgcmp-d
  loadBalancer:
    addressPools:
    - addresses:
      - 192.168.120.64/26
      name: loadBalancerAddressPool-1
    mode: bundled
    ports:
      controlPlaneLBPort: 443
    vips:
      controlPlaneVIP: 192.168.120.16
      ingressVIP: 192.168.120.64
  nodeConfig:
    containerRuntime: containerd
    podDensity:
      maxPodsPerNode: 250
  profile: default
