---
- name: Create Anthos cluster workspace directory
  become_user: "{{ gem_user }}"
  file:
    path: "{{ gem_home }}/bmctl-workspace/{{ cluster_name }}"
    state: directory
    owner: "{{ gem_user }}"
    group: "{{ gem_user }}"

- name: Create cluster configuration template in workspace
  become_user: "{{ gem_user }}"
  template:
    src: cluster.yaml.j2
    dest: "{{ gem_home }}/bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}.yaml"

- name: Deploy the GDC Hybrid Cluster
  become_user: "{{ gem_user }}"
  command: "bmctl create cluster -c {{ cluster_name }}"
  args:
    chdir: "{{ gem_home }}"
    creates: "{{ gem_home }}/bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}-kubeconfig"
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: "{{ gem_home }}/bm-gcr.json"
  async: 3600
  poll: 60
  register: cluster_create

- name: Display cluster creation output
  debug:
    var: cluster_create.stdout_lines
  when: cluster_create is defined and cluster_create.stdout_lines is defined

- name: Create ClusterRoleBinding for GKE Connect Gateway access
  become_user: "{{ gem_user }}"
  shell: |
    cat <<EOF | kubectl --kubeconfig {{ gem_home }}/bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}-kubeconfig apply -f -
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: gcp-sa-cluster-admin-binding
    subjects:
    - kind: User
      name: {{ gcp_cluster_admin_sa }}
    roleRef:
      kind: ClusterRole
      name: cluster-admin
      apiGroup: rbac.authorization.k8s.io
    EOF
  when: cluster_create is not failed

