# Copyright 2026 Google LLC / Kroger Cloud Engineering
# Zero-Trust Network Segmentation Policy: PCI-DSS v4.0 Compliance
# Blocks out-of-scope store apps from sweeping PCI Cardholder Data Environment (CDE)

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pci-cde-zero-trust-isolation
  namespace: cde-pci-scope
spec:
  podSelector:
    matchLabels:
      security-scope: pci-cde
  policyTypes:
  - Ingress
  ingress:
  # Allow traffic ONLY from authorized tokenization proxy or POS engines on port 80/8443
  - from:
    - namespaceSelector:
        matchLabels:
          name: store-ops-non-pci
      podSelector:
        matchLabels:
          app: toshiba-elera
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 8443
