---
- name: Install required packages
  apt:
    name:
      - bridge-utils
      - jq
    state: present
    update_cache: yes

- name: Ensure platform user exists for Traefik
  user:
    name: "{{ gem_user }}"
    state: present
    shell: /bin/bash

- name: Install Traefik
  import_role:
    name: workstation
    tasks_from: traefik.yaml

- name: Allow IP forwarding globally
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
