---
gdc_user: "gdc"
gdc_home: "/home/{{ gdc_user }}"
pod_cidrBlocks: "10.0.0.0/17"
services_cidrBlocks: "10.96.0.0/12"
maxPodsPerNode: 250

# GCP Service Account to grant cluster-admin access via GKE Connect Gateway
gcp_cluster_admin_sa: "gem-cluster-admin@{{ gcp_project_id }}.iam.gserviceaccount.com"

cluster_node_taints:
  - key: "node-role.kubernetes.io/master"
    effect: "PreferNoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    effect: "PreferNoSchedule"

# OPA Gatekeeper release version for validation and mutation
gatekeeper_version: "v3.22.0"

secondary_networks:
  - name: "vlan-123"
    vlan_id: 123
    subnet: "172.16.10.0/24"
    gateway: "172.16.10.1"
    vip_pool: "172.16.10.200-172.16.10.250"
  - name: "vlan-456"
    vlan_id: 456
    subnet: "192.168.45.0/24"
    gateway: "192.168.45.1"
    vip_pool: "192.168.45.200-192.168.45.250"
